### ISSUE TITLE
Netbox 3.6 Current Config -> 'NoneType' object has no attribute '_meta'

### ISSUE THREAD

**Issue by D1StrX** [peteeckel/netbox-plugin-dns#56]
Python version: 3.10.12
NetBox version: 3.6.0
Plugins: 
  netbox_dns: 0.18.10

**Describe the bug**
After updating to Netbox 3.6 and clicking on the Admin -> Configuration/Current Config
```
<class 'AttributeError'>

'NoneType' object has no attribute '_meta'
NetBox version: 3.6.0
Plugins: 
  netbox_dns: 0.18.10
```

**To Reproduce**
1. Go to 'Admin'
2. Click on 'Current Config'
3. See error
```
<class 'AttributeError'>

'NoneType' object has no attribute '_meta'
NetBox version: 3.6.0
Plugins: 
  netbox_dns: 0.18.10
```

**Expected result**
Hopefully minor update to work on Netbox 3.6 😄 

**Actual result**
As the bug describes

**Comment by peteeckel** [comment]
That's a NetBox 3.6.0 bug (fixed in 3.6.1): https://github.com/netbox-community/netbox/issues/13655
