### ISSUE TITLE
NetBox cannot start due to import error

### ISSUE THREAD

**Issue by lukoerfer** [peteeckel/netbox-plugin-dns#90]
**Versions**
NetBox Version: 3.5.8
NetBox DNS Version: 0.20.2
Python Version: 3.10

**Describe the bug**
NetBox fails to start after installation (and activation in `configuration.py`) of the plugin and shows the following error:
> `ImportError: cannot import name 'get_plugin_config' from 'extras.plugins' (/opt/netbox/netbox/extras/plugins/__init__.py)`

When the plugin is deactivated in `configuration.py`, NetBox will start again.

**Code Examples**
The error seems to be caused by a wrong import in `middleware.py`, because `get_plugin_config` is imported from `extras.plugins` instead of `extras.plugins.utils`. In other files (e.g. `__init__.py` and `models.py`) the import is correct. Once this import is fixed (like I did directly inside my installed pip packages), NetBox will successfully start with the loaded plugin.

**Comment by peteeckel** [comment]
HI @lukoerfer, probably you previously had the old `netbox-dns` PyPI module installed. 

Just run `pip uninstall` on it and try again.

**Comment by lukoerfer** [comment]
Thanks for the fast response!

> The strange thing is that it *does* work with NetBox 3.6.x ...

I just took a deeper look into the netbox sources and it seems like they added a wildcard import for `utils` right in version 3.5.9:
https://github.com/netbox-community/netbox/commit/3c0a3ca703d31c9571279efa1519d43e09a94042

It was a really unlucky combination that I installed NetBox a few months ago and now tried to evaluate this plugin without updating NetBox first.

**Comment by peteeckel** [comment]
NetBox 3.5.8 was a major mess. 

After it came out and broke the import for `get_plugin_config` I (and all other plugin authors using it) had to patch their plugins to stay compatible, breaking compatibility with NetBox 3.5.0 to 3.5.7. Obviously the core team fixed it in 3.5.9, so now there is the option to remove the fix (breaking compatibility with 3.5.8 and potentially versions after 3.6.x) or leave it in and support only NetBox 3.5.8+.

The alternative is not much more attractive, but possibly I'll do it anyway to solve the dilemma:
```
try:
    # NetBox 3.5.0 - 3.5.7, 3.5.9+
    from extras.plugins import get_plugin_config
except ImportError:
    # NetBox 3.5.8
    from extras.plugins.utils import get_plugin_config
```
